### ISSUE TITLE
Test Dataset in test.py

### ISSUE THREAD

**Issue by pmwachira** [camoverride/language-classifier#1]
The below code reads from a dataset that we did not create in the tutorial,kindly advise on how to go about this:
```
TEST_DATA = []
for language in LANGUAGES:
    TEST_DATA.append(
        np.array([open('scraper/data/' + language + '/TEST_SET.db').read()])
    )
```

**Comment by camoverride** [comment]
I just overhauled this project and am closing this issue because this piece of code if no longer used!
